### PR TITLE
Fix types for Webpack Plugin

### PR DESCRIPTION
**Pull request by Connormiha**
Add `apply` method in types

### CODE REVIEW

**Comment by zoobestik** [comment]
@Connormiha, thanks for your pull request.
I have convert [`.ts —> .flow`](https://github.com/zoobestik/csso-webpack-plugin/blob/dev/package.json#L37), and I will check it little bit later.

Do you use `.ts` for webpack config? :)

**Comment by Connormiha** [comment]
Yes, i use `webpack.config.ts`

**Comment by 43081j** [comment]
@zoobestik could you possibly publish a new version so we can get this fix? 🙏

**Comment by zoobestik** [comment]
**Fixed in [2.0.0-beta.2](https://github.com/zoobestik/csso-webpack-plugin/releases/tag/v2.0.0-beta.2)**

/cc @43081j

**Pull request merged**
